user1 = User.create(first_name: "Greg", last_name: "Something", home_location: "Boston", email: "something@nothing.com", password: "password123")
User.create(first_name: "Greg", last_name: "Ward", home_location: "Boston", email: "greg@la.com", password: "password1", role: "admin")

Location.create(name: "New York City", state: "NY", description: "The Big Apple", user: user1)
Location.create(name: "San Francisco", state: "CA", description: "The city by the Bay", user: user1)
Location.create(name: "Boston", state: "MA", description: "The Cradle of Liberty", user: user1)
Location.create(name: "Los Angeles", state: "CA", description: "City of Angels", user: user1)
Location.create(name: "Anchorage", state: "AK", description: "City of Lights and Flowers", user: user1)
Location.create(name: "Chicago", state: "IL", description: "The Windy City", user: user1)
Location.create(name: "San Juan", state: "PR", description: "La Ciudad Amurallada", user: user1)
Location.create(name: "Houston", state: "TX", description: "We have a problem.", user: user1)
Location.create(name: "Portland", state: "OR", description: "Keep Portland Weird", user: user1)
Location.create(name: "Phoenix", state: "AZ", description: "Arizona's Urban Heart", user: user1)
Location.create(name: "Honolulu", state: "HI", description: "The Big Pineapple", user: user1)
Location.create(name: "Chico", state: "CA", description: "Go Wildcats!", user: user1)
Location.create(name: "Seattle", state: "WA", description: "Coffee Capital of the World", user: user1)
Location.create(name: "Providence", state: "RI", description: "America's Renaissance City", user: user1)
Location.create(name: "Hanover", state: "NH", description: "Live Free or Die Hard", user: user1)
Location.create(name: "Detroit", state: "MI", description: "Mo-Town", user: user1)
Location.create(name: "Gilroy", state: "CA", description: "Garlic Capital of the World", user: user1)
Location.create(name: "Denver", state: "CO", description: "The Mile-High City", user: user1)
Location.create(name: "Atlanta", state: "GA", description: "The A-T-L", user: user1)
Location.create(name: "Wichita", state: "KS", description: "The Emerald City", user: user1)
Location.create(name: "Reno", state: "NV", description: "The Biggest Little City", user: user1)
Location.create(name: "Las Vegas", state: "NV", description: "Sin City", user: user1)
Location.create(name: "New Orleans", state: "LA", description: "The Big Easy", user: user1)
Location.create(name: "Cambridge", state: "MA", description: "The People's Republic of Cambridge", user: user1)
Location.create(name: "Kansas City", state: "MO", description: "Paris of the Plains", user: user1)
Location.create(name: "Bozeman", state: "MT", description: "The Bozone", user: user1)
Location.create(name: "Franklin", state: "NJ", description: "Fluorescent Mineral Capital of the World", user: user1)
Location.create(name: "Portland", state: "ME", description: "Forest City", user: user1)
Location.create(name: "Sarasota", state: "FL", description: "Heaven's Waiting Room", user: user1)
Location.create(name: "Beaver", state: "OK", description: "Cow Chip Capital of the World", user: user1)
Location.create(name: "Philadelphia", state: "PA", description: "The City of Brotherly Love", user: user1)
Location.create(name: "Charleston", state: "SC", description: "The Big Sweet Grass Basket", user: user1)
Location.create(name: "Rapid City", state: "SD", description: "Real America Up Close", user: user1)
Location.create(name: "Columbia", state: "TN", description: "Mule Capital of the World", user: user1)
Location.create(name: "Washington", state: "DC", description: "Hollywood for Ugly People", user: user1)
Location.create(name: "Ellsworth", state: "WI", description: "Cheese Curd Capital of Wisconsin", user: user1)
Location.create(name: "Dallas", state: "TX", description: "The Big D", user: user1)
Location.create(name: "Austin", state: "TX", description: "Bat City", user: user1)
Location.create(name: "Baltimore", state: "MD", description: "The City that Reads", user: user1)
Location.create(name: "Boise", state: "ID", description: "The City of Trees", user: user1)
Location.create(name: "Berkeley", state: "CA", description: "Berzerkeley", user: user1)
Location.create(name: "Orlando", state: "FL", description: "Hell", user: user1)
Location.create(name: "San Diego", state: "CA", description: "City in Motion", user: user1)
Location.create(name: "Salem", state: "MA", description: "The Witch City", user: user1)
Location.create(name: "Salem", state: "MO", description: "Charcoal Capital of the World", user: user1)
Location.create(name: "Salem", state: "OR", description: "The Cherry City", user: user1)
Location.create(name: "Salem", state: "NH", description: "Gateway to New Hampshire", user: user1)
Location.create(name: "Dannebrog", state: "NE", description: "Danish Capital of Nebraska", user: user1)
Location.create(name: "Jackson", state: "MS", description: "Chimneyville", user: user1)
Location.create(name: "Aspen", state: "CO", description: "America's Canary City", user: user1)
Location.create(name: "Stockton", state: "CA", description: "Asparagus Capital of the World", user: user1)
