Location.create(name: "New York City", state: "NY", description: "The Big Apple")
Location.create(name: "San Francisco", state: "CA", description: "The city by the Bay")
Location.create(name: "Boston", state: "MA", description: "The Cradle of Liberty")
Location.create(name: "Los Angeles", state: "CA", description: "City of Angels")
Location.create(name: "Anchorage", state: "AK", description: "City of Lights and Flowers")
Location.create(name: "Chicago", state: "IL", description: "The Windy City")
Location.create(name: "San Juan", state: "PR", description: "La Ciudad Amurallada")
Location.create(name: "Houston", state: "TX", description: "We have a problem.")
Location.create(name: "Portland", state: "OR", description: "Keep Portland Weird")
Location.create(name: "Phoenix", state: "AZ", description: "Arizona's Urban Heart")
Location.create(name: "Honolulu", state: "HI", description: "The Big Pineapple")
Location.create(name: "Chico", state: "CA", description: "Go Wildcats!")
Location.create(name: "Seattle", state: "WA", description: "Coffee Capital of the World")
Location.create(name: "Providence", state: "RI", description: "America's Renaissance City")
Location.create(name: "Hanover", state: "NH", description: "Live Free or Die Hard")
Location.create(name: "Detroit", state: "MI", description: "Mo-Town")
Location.create(name: "Gilroy", state: "CA", description: "Garlic Capital of the World")
Location.create(name: "Denver", state: "CO", description: "The Mile-High City")
Location.create(name: "Atlanta", state: "GA", description: "The A-T-L")
Location.create(name: "Wichita", state: "KS", description: "The Emerald City")
Location.create(name: "Reno", state: "NV", description: "The Biggest Little City")
Location.create(name: "Las Vegas", state: "NV", description: "Sin City")
Location.create(name: "New Orleans", state: "LA", description: "The Big Easy")
Location.create(name: "Cambridge", state: "MA", description: "The People's Republic of Cambridge")
Location.create(name: "Kansas City", state: "MO", description: "Paris of the Plains")
Location.create(name: "Bozeman", state: "MT", description: "The Bozone")
Location.create(name: "Franklin", state: "NJ", description: "Fluorescent Mineral Capital of the World")
Location.create(name: "Portland", state: "ME", description: "Forest City")
Location.create(name: "Sarasota", state: "FL", description: "Heaven's Waiting Room")
Location.create(name: "Beaver", state: "OK", description: "Cow Chip Capital of the World")
Location.create(name: "Philadelphia", state: "PA", description: "The City of Brotherly Love")
Location.create(name: "Charleston", state: "SC", description: "The Big Sweet Grass Basket")
Location.create(name: "Rapid City", state: "SD", description: "Real America Up Close")
Location.create(name: "Columbia", state: "TN", description: "Mule Capital of the World")
Location.create(name: "Washington", state: "DC", description: "Hollywood for Ugly People")
Location.create(name: "Ellsworth", state: "WI", description: "Cheese Curd Capital of Wisconsin")
Location.create(name: "Dallas", state: "TX", description: "The Big D")
Location.create(name: "Austin", state: "TX", description: "Bat City")
Location.create(name: "Baltimore", state: "MD", description: "The City that Reads")
Location.create(name: "Boise", state: "ID", description: "The City of Trees")
Location.create(name: "Berkeley", state: "CA", description: "Berzerkeley")
Location.create(name: "Orlando", state: "FL", description: "Hell")
Location.create(name: "San Diego", state: "CA", description: "City in Motion")
Location.create(name: "Salem", state: "MA", description: "The Witch City")
Location.create(name: "Salem", state: "MO", descripton: "Charcoal Capital of the World")
Location.create(name: "Salem", state: "OR", description: "The Cherry City")
Location.create(name: "Salem", state: "NH", description: "Gateway to New Hampshire")
Location.create(name: "Dannebrog", state: "NE", description: "Danish Capital of Nebraska")
Location.create(name: "Jackson", state: "MS", description: "Chimneyville")
Location.create(name: "Aspen", state: "CO", description: "America's Canary City")
Location.create(name: "Stockton", state: "CA", description: "Asparagus Capital of the World")

User.create(first_name: "Greg", last_name: "Something", home_location: "Boston", email: "something@nothing.com", password: "password123")
User.create(first_name: "Greg", last_name: "Ward", home_location: "Boston", email: "greg@la.com", password: "password1", role: "admin")
