Location.create(name: "New York City", state: "NY", description: "The Big Apple")
Location.create(name: "San Francisco", state: "CA", description: "The city by the Bay")
Location.create(name: "Boston", state: "MA", description: "The Cradle of Liberty")
Location.create(name: "Los Angeles", state: "CA", description: "City of Angels")
Location.create(name: "Anchorage", state: "AK", description: "City of Lights and Flowers")
Location.create(name: "Chicago", state: "IL", description: "The Windy City")
Location.create(name: "San Juan", state: "PR", description: "La Ciudad Amurallada")
Location.create(name: "Houston", state: "TX", description: "We have a problem.")
Location.create(name: "Portland", state: "OR", description: "Keep Portland Weird")
Location.create(name: "Phoenix", state: "AZ", description: "Arizona's Urban Heart")
Location.create(name: "Honolulu", state: "HI", description: "The Big Pineapple")
Location.create(name: "Chico", state: "CA", description: "Go Wildcats!")
Location.create(name: "Seattle", state: "WA", description: "Coffee Capital of the World")
Location.create(name: "Providence", state: "RI", description: "America's Renaissance City")
Location.create(name: "Hanover", state: "NH", description: "Live Free or Die Hard")
Location.create(name: "Detroit", state: "MI", description: "Mo-Town")
Location.create(name: "Gilroy", state: "CA", description: "Garlic Capital of the World")
Location.create(name: "Denver", state: "CO", description: "The Mile-High City")
Location.create(name: "Atlanta", state: "GA", description: "The A-T-L")
Location.create(name: "Wichita", state: "KS", description: "The Emerald City")
Location.create(name: "Reno", state: "NV", description: "The Biggest Little City")
Location.create(name: "Las Vegas", state: "NV", description: "Sin City")
Location.create(name: "New Orleans", state: "LA", description: "The Big Easy")
Location.create(name: "Cambridge", state: "MA", description: "The People's Republic of Cambridge")
Location.create(name: "Kansas City", state: "MO", description: "Paris of the Plains")
Location.create(name: "Bozeman", state: "MT", description: "The Bozone")
Location.create(name: "Franklin", state: "NJ", description: "Fluorescent Mineral Capital of the World")
Location.create(name: "Portland", state: "ME", description: "Forest City")
Location.create(name: "Sarasota", state: "FL", description: "Heaven's Waiting Room")

User.create(first_name: "Greg", last_name: "Something", home_location: "Boston", email: "something@nothing.com", password: "password123")
User.create(first_name: "Greg", last_name: "Ward", home_location: "Boston", email: "greg@la.com", password: "password1", role: "admin")
